Feat/client admin agenda create
sparcs-kaist/biseo pull request #18
Opened 2023-07-07 13:12 UTC by kjy2844

2023-07-12 08:58 UTC, SnowSuno requested changes
pr 리뷰 중 api interface에도 변경이 필요한 부분이 있는 것 같아 코멘트했습니다.
작업하신 분 외 다른 분들도 한번씩 보시면 좋을 것 같고 자세한 내용은 리뷰 코멘트에서 확인하실 수 있습니다!

2023-07-21 14:01 UTC, donghyo1234 commented on client/src/services/admin-agenda.ts
> +    // TODO: handle local id
주석 삭제 했습니다

2023-07-21 14:03 UTC, donghyo1234 commented on client/src/services/admin-agenda.ts
> +socket.on("admin.agenda.created", (adminAgenda) => {
일단은 서버에서 어드민에게 보내주면 보내주면 문제 없다고 생각했습니다. 이슈 생기면 수정하겠습니당.

2023-07-21 14:04 UTC, donghyo1234 commented on client/src/services/admin-agenda.ts
> +});
명시적으로 바꾸도록 수정했습니다

2023-07-21 14:04 UTC, donghyo1234 commented on client/src/services/admin-agenda.ts
> +      adminAgendas: newAdminAgendas,
명시적 업데이트로 수정했습니다

2023-07-24 15:45 UTC, prectal123 approved these changes
LGTM

2023-07-24 15:47 UTC, SnowSuno approved these changes
LGTM

2023-07-24 15:48 UTC, merged