feat(agenda): complete first draft
sparcs-kaist/biseo pull request #19
Opened 2023-07-09 10:03 UTC by minjoo0729

1. TODO: Verify that this code is written as intended
2. TODO: Handle error for voteAgenda
3. TODO: Handle error for retrieveAgenda
4. TODO: Fix the alert algorithm according to the design

2023-07-10 13:09 UTC, SnowSuno commented
Indent가 4로 설정된 걸 보니 뭔가 `prettier` 설정이 제대로 안된 것 같아요

2023-07-14 18:20 UTC, SnowSuno requested changes

2023-07-14 18:20 UTC, SnowSuno commented on client/src/services/agenda.ts
> +});
여기에서 `socket`이 `BiseoSocket` 타입을 가지고 있는데, 여기에서 각 이벤트에 대한 핸들러 타입을 모두 가지고 있기 때문에 핸들러의 변수인 `ongoingAgenda` 또한 명시적으로 지정해 주지 않아도 자동으로 infer 됩니다. 

```suggestion
socket.on("agenda.started", (ongoingAgenda) => {
  useAgenda.setState((state) => ({
    agendas: [...state.agendas, ongoingAgenda],
  }));
});
```

이와 같이 implicit하게 타입을 정의할 수 있는 경우에는 보통 이를 명시적으로 나타내지 않는 것이 best practice로 취급되고, 또한 추후 API 변경에도 유연하게 대응할 수 있기 때문에 명시하지 않는 것이 맞는 것 같습니다. 

관련 typescript type inference 관련해서 읽어보면 좋을 것 같은 자료입니다. 
- https://www.typescriptlang.org/docs/handbook/type-inference.html

2023-07-14 18:20 UTC, SnowSuno commented on client/src/services/agenda.ts
> +socket.on("agenda.voted", (voted: Voted) => {
```suggestion
socket.on("agenda.voted", (voted) => {
```
여기도 동일

2023-07-14 18:20 UTC, SnowSuno commented on client/src/services/agenda.ts
> +socket.on("agenda.terminated", (terminatedAgenda: TerminatedAgenda) => {
```suggestion
socket.on("agenda.terminated", (terminatedAgenda) => {
```
여기도 동일

2023-07-14 18:20 UTC, SnowSuno commented on client/src/services/agenda.ts
> +socket.on("agenda.reminded", (reminded: Reminded) => {
```suggestion
socket.on("agenda.reminded", (reminded) => {
```
여기도 동일

2023-07-17 15:29 UTC, kjy2844 approved these changes
LGTM

2023-07-17 15:56 UTC, SnowSuno approved these changes
LGTM 👍

2023-07-19 01:36 UTC, merged