feat(admin-agenda): fix api fit to schema
sparcs-kaist/biseo pull request #20
Opened 2023-07-10 14:29 UTC by prectal123

Codes about Admin-Agenda Back end

- [x] Remind Service Logic
- [x] Remind Listener Logic
- [x] Trim Variable Names
- [x] Apply Debug-Purpose Client Code (Non-Commit)
- [x] Test Remind Code

2023-07-21 15:57 UTC, prectal123 commented on server/src/service/admin.agenda.ts
기존의 타입 구조에서 변형을 일으키지 않고 원하는 정보 만을 전달할 방법으로, voters variable이 담고 있는 array의 첫 원소의 id에 선택지의 투표 수를 저장하는 방법을 사용했습니다. 필요하다면 이 부분을 완전히 빈칸으로 바꿀 수도 있습니다.

2023-07-26 04:48 UTC, kjy2844 commented on server/src/service/admin.agenda.ts
> +    return organizedAgenda;
find해서 return하는 것까지 복잡하게 되어있는데, 
시작하지 않은 agenda만 update가 가능하니까 agendaCreate와 비슷하게 처리할 수 있을 것 같아요.

```typescrip
    const { subtitle, choices, voters, ...agendaProps } =
      await prisma.agenda.update({
        where: {
            id: agendaUpdate.id,
          },
        data: {
          title: agendaUpdate.title,
          subtitle: agendaUpdate.resolution,
          content: agendaUpdate.content,
          choices: {
            createMany: {
              data: agendaUpdate.choices.map((it) => ({ name: it })),
            },
          },
          voters: {
            createMany: {
              data: agendaUpdate.voters.total.map((it) => ({
                userId: it,
              })),
            },
          },
        },
        select: {
          id: true,
          title: true,
          subtitle: true,
          content: true,
          choices: true,
          voters: {
            include: {
              user: {
                select: {
                  id: true,
                  username: true,
                  displayName: true,
                },
              },
            },
          },
        },
      });
      return {
        ...agendaProps,
        resolution: subtitle,
        status: "preparing",
        choices: choices.map((choice) => ({
          id: choice.id,
          name: choice.name,
          voters: [],
          count: 0,
        })),
        voters: {
          voted: [],
          total: voters.map((voter) => voter.user),
        },
      };
```

2023-07-26 04:51 UTC, kjy2844 commented on server/src/service/admin.agenda.ts
>        let status: "ongoing" | "preparing" | "terminated" = "ongoing";
status의 타입을 이미 공통으로 사용하기 위해 정의해두었으니까 schema.AdminAgendaStatus로 적어주면 좋을 것 같습니다.

2023-07-26 05:12 UTC, kjy2844 commented on server/src/service/admin.agenda.ts
> +      }
```typescript
{
  id: voter.user.id,
  username: voter.user.username,
  displayName: voter.user.displayName,
},
``` 
이 부분을 `voter.user`로 변경할 수 있을 것 같습니다.

혹은 전체를 flatMap으로 간단하게 작성할 수 있을 것 같습니다.
```typescript
const voted = agenda.choices.flatMap(choice => choice.users.map(userChoice => userChoice.user));
```

2023-07-26 05:15 UTC, kjy2844 commented on server/src/service/admin.agenda.ts
>              name: choice.name,
함수에 return문만 있다면 return을 명시적으로 작성하지 않아도 괜찮습니다.
단, 객체의 경우는 소괄호로 한 번 감싸주어야 합니다.

```typescript
agenda.choices.map((choice) => ({
    id: choice.id,
    name: choice.name,
    count: choice.users.length,
})),
```

2023-07-26 05:29 UTC, kjy2844 commented on server/src/listener/admin.agenda.ts
> +  }
https://socket.io/docs/v4/emit-cheatsheet/ 에 따르면 
socket io에서 여러 방에 보낼 때, 각 방의 이름을 array에 넣어 io.to의 인자로 전달할 수 있습니다. 
이렇게 활용할 수 있을 것 같습니다.

```
  // to all clients in room1 and/or room2 except those in room3
  io.to(["room1", "room2"]).except("room3").emit(/* ... */);
```

``` suggestion typescript
io.to(res.users.map(user => `user/${user}`)).emit("agenda.reminded", {...});
```

2023-07-26 08:12 UTC, SnowSuno requested changes

2023-07-26 08:12 UTC, SnowSuno commented on server/src/service/admin.agenda.ts
> +  users: string[];
변수명은 `users`인데 타입이 `string[]`이면 이것이 user의 정확히 어떤 것인지(id인지, username인지, displayName인지 등) 알기 힘들 것 같아요. `userIds`, `usernames`, `userDisplayNames` 등의 변수명을 사용하는게 조금 더 직관적인 것 같아요. 

이 상황에서는 username의 array를 리턴하는 것이니 `usernames`가 적절해 보이네요.

```suggestion
  usernames: string[];
```

2023-07-26 08:12 UTC, SnowSuno commented on server/src/service/admin.agenda.ts
> +    return { users: unvoters, agendaID: id, message: message };
이와 같이 모든 관련 항목을 가져온 뒤 js로 aggregate하는 것보다는 처음부터 unvoted users를 가져오는 쿼리를 작성하는 것이 코드 가독성 면에서도 퍼포먼스 면에서도 더 좋을 것 같아요!

```typescript
const unvotedUsers = await prisma.user.findMany({
  select: { username: true },
  where: {
    agendas: { some: { agendaId: id } },
    NOT: { choices: { some: { choice: { agendaId: id } } } },
  },
});
```

다만 agendaId가 실제 존재하는 ID인지 validate 해주는 로직은 살려둬야겠네요.

2023-07-26 08:18 UTC, prectal123 commented on server/src/service/admin.agenda.ts
> +    if (!voteInfo) return { users: [], agendaID: id, message: message };
이 부분 같은 경우에는 Null이 반환될 경우 Listener 쪽에서 에러를 Throw 하는 것으로 통일되어 있습니다.

2023-07-27 05:52 UTC, merged