Feat/server agenda
sparcs-kaist/biseo pull request #21
Opened 2023-07-14 09:17 UTC by Ariaspect

2023-07-21 14:56 UTC, kjy2844 requested changes

2023-07-21 14:56 UTC, kjy2844 commented on server/src/service/agenda.ts
> +  const agenda_dbres = await prisma.agenda.findMany({
snake case가 아니라 camel case로 변수명을 써주면 좋을 것 같습니다.

```suggestion
  const agendas = await prisma.agenda.findMany({
```

2023-07-21 14:56 UTC, kjy2844 commented on server/src/service/agenda.ts
> +    let status: "ongoing" | "preparing" | "terminated" = "ongoing";
`status`의 타입으로 `AgendaStatus`를 사용하면 좋을 것 같습니다.

2023-07-21 14:56 UTC, kjy2844 commented on server/src/service/agenda.ts
> +      userId: 0, // TODO: How to get userId without `user`?
user 정보를 이용해서 userId를 채워줘야 할 것 같습니다.

2023-07-24 16:00 UTC, babycroc commented on server/src/listener/agenda.ts
제가 chat backend 작업할 때 (PR#16 참고) 순호가 여기서 BiseoError 쓰지 말고 에러 처리를 service 딴의 retrieveAll, vote 함수에서 하라고 했는데..! (어차피 에러는 글로벌하게 처리되게 해놨으니까) 뭔가 자세한 이유는 순호가 얘기해줄거에요 ㅇ.ㅇ

2023-07-25 01:10 UTC, minjoo0729 requested changes

2023-07-25 20:54 UTC, SnowSuno requested changes
DB에서 가져오는 쿼리를 최적화하거나, 코드 퀄리티를 높일 수 있는 방법에 중점해서 리뷰했어요.

개선하면 좋을 것 같은 사항들도 모두 적어둔 거라 모두 이번 PR에서 해결할 필요는 없지만, 이후 코드를 작성하면서 비슷한 상황이 나왔을 때 도움이 될 것 같은 부분들이 많아서 상세하게 적어 봤습니당!

이 PR 작업자가 아니시더라도 다른 분들도 한번씩 읽어 봐도 좋을 것 같아요!

2023-07-25 20:54 UTC, SnowSuno commented on server/src/service/agenda.ts
> +    });
이부분 쿼리도 개선을 하긴 해야 할 것 같네요. 이부분은 @kjy2844님이 저랑 논의했던 내용대로 개선해주시면 될 것 같아용

2023-07-25 20:54 UTC, SnowSuno commented on server/src/service/agenda.ts
> +  if (isUserVotable && isChoiceInAgenda) {
이부분을 nesting하는 것보다는 early return을 사용하여 nesting을 줄이고 가독성을 향상시킬 수 있을 것 같아요. 
```suggestion
  if (!await prisma.userAgendaVotable.count({
    where: {
      userId: user.id,
      agendaId: agendaId,
    },
  })) throw new BiseoError("Do not have permissions to vote to this agenda");
  
  if (!await prisma.choice.count({
    where: {
      id: choiceId,
      agendaId: agendaId,
    },
  })) throw new BiseoError("Already voted for this agenda");
  
```

이와 같이 개선하면 Client 쪽에도 조금 더 상세한 에러를 줄 수 있을 것 같네요!

그때 톡방에 올린 적이 있었던 [이 영상](https://www.youtube.com/watch?v=CFRhGnuXG-4)의 리팩토링 방법을 실제 적용해 볼 수 있는 사례인 것 같아요!

2023-07-25 20:54 UTC, SnowSuno commented on server/src/service/agenda.ts
> +    if (!res) throw new BiseoError("failed to vote");
이 부분은 "failed to vote"이라는 에러에서 말하고자 하는 바가 명확하지 않은 것 같아요! 이런 상황을 개선할 수 있는 방안이 몇 가지가 있어요.

- 에러 상황이 명확한 경우: 에러 메시지가 그 상황을 더 잘 설명하도록 개선한다. 
- 에러가 너무 많은 케이스를 커버하여 명확하지 않은 경우: 상황을 각각 나누어 각각의 케이스를 핸들링하도록 하고 각각의 에러 메시지를 작성한다. 
- 이 외의 경우(명확하지 않은 일반적인 에러를 핸들링하려 하는 경우, 로직 전체에 대한 try-catch 문 등): 
이 경우는 굳이 불명확한 에러 메시지를 주려 하는 것보다 global error나 다름 없는 redundant한 에러인 경우가 대부분이기 때문에 global error handler에게 넘겨주는 것이 적절할 것 같습니다. 

이 상황에서는 위 코멘트의 방식으로 두 가지 에러를 핸들링하고, 나머지는 global error handler에게 넘겨주면 될 것 같아요!
```suggestion
```

2023-07-26 04:33 UTC, kjy2844 commented on server/src/service/agenda.ts
> +  if (isUserVotable && isChoiceInAgenda) {
저 count하는 쿼리를 if문의 조건으로 그냥 적으면 왜 검사한건지 알기 어려울 것 같아요.
지금처럼 변수명을 명확히 적어주거나, 주석을 남겨서 어떤 조건을 검사하고 싶었는지 보여주면 좋을 것 같아요.

2023-07-26 04:35 UTC, kjy2844 commented on server/src/service/agenda.ts
> +    if (!res) throw new BiseoError("failed to vote");
그럼 DB에 쿼리하는 부분에서 발생하는 에러는 따로 try-catch로 감싸지 않고 global error handler가 처리하도록 남겨두면 될까요?

2023-07-26 06:47 UTC, SnowSuno commented on server/src/service/agenda.ts
> +  if (isUserVotable && isChoiceInAgenda) {
앗 저 리뷰의 의도는 그걸 말하려는게 아니라
```
if (조건 & 조건) {
  // 메인 로직
}
```
형태보다 
```
if (!조건) throw;
if (!조건) throw;

// 메인 로직
```
과 같은 식으로 코드를 구성했을 때 로직을 더 잘 정리할 수 있다는 뜻이었어요.

변수명을 유지하는 방식으로 구조를 그렇게 변경하면 이렇게 되겠네요.
```suggestion
  const isUserVotable = !!(await prisma.userAgendaVotable.count({
    where: {
      userId: user.id,
      agendaId: agendaId,
    },
  }));
  if (!isUserVotable) throw new BiseoError("Do not have permissions to vote to this agenda");

  const isChoiceInAgenda = !!(await prisma.choice.count({
    where: {
      id: choiceId,
      agendaId: agendaId,
      NOT: { users: { some: { userId: user.id } } },
    },
  }));
  if (!isChoiceInAgenda) throw new BiseoError("Invalid choice");


```

2023-07-26 06:48 UTC, SnowSuno commented on server/src/service/agenda.ts
> +  if (isUserVotable && isChoiceInAgenda) {
앗 그리고 전 리뷰에서는 발견하지 못했는데 유저가 이미 투표했는지에 대한 validation이 추가되어야 할 것 같네요
```typescript
  const userVoted = !!(await prisma.userChoice.count({
    where: {
      userId: user.id,
      choiceId: choiceId,
    }
  }));
  if (userVoted) throw new BiseoError("Already voted for this agenda");
```

2023-07-26 06:56 UTC, SnowSuno commented on server/src/service/agenda.ts
> +    if (!res) throw new BiseoError("failed to vote");
그 부분은 무슨 쿼리냐에 따라 다를 것 같아요.

만약 id로 어떤 item을 조회해 오는 쿼리에서 '해당 id를 가진 item이 없는 경우'라면 `"Not found"`과 같은 에러를 명시적으로 내려주는 것이 맞을 것 같고, 

그냥 단순히 '쿼리가 어떤 이유로 실패할지 모른다'는 locally try-catch로 잡아봤자 유의미한 정보를 client에게 내려줄 수 없기 때문에 사실상 global error와 다른게 없는 redundant한 작업이라고 생각합니당

HTTP status `400`대와 `500`대 에러의 차이 정도로 생각하면 될 것 같습니당. 

***
이와 별개로 저 코드 줄에서 `res`의 타입은 `null`이 되지 않기 때문에 저 줄은 무조건 실행되지 않는 코드입니당.

2023-07-26 07:39 UTC, kjy2844 commented on server/src/service/agenda.ts
> +  if (isUserVotable && isChoiceInAgenda) {
아 그렇네요. 이미 투표했는지도 확인해야겠네요.

2023-07-26 11:56 UTC, Ariaspect commented on server/src/service/agenda.ts
> +        ),
_sum 은 이미 DB에 존재하는 number field 에 대해서만 사용이 가능하고 저 부분은 choice.users의 length(count) 를 합쳐야 하기 때문에 사용하기 어려울 것 같습니다.

2023-07-27 05:19 UTC, kjy2844 approved these changes

2023-07-27 05:52 UTC, merged