feat(ui): implement chat container and message ui
sparcs-kaist/biseo pull request #24
Opened 2023-07-26 08:31 UTC by babycroc

2023-07-27 08:15 UTC, babycroc commented
biseo-interface/chat 에 Notice 관련 타입 없음

2023-08-01 08:04 UTC, babycroc commented
<img width="423" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/33417582/797a0831-dc90-4b23-a30d-c4ba9a600c97">

2023-08-01 08:23 UTC, babycroc commented
<img width="300" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/33417582/5a5fe9ca-c98c-4053-9946-ba6d21c81eaf"><img width="300" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/33417582/8c0adf3a-f089-430e-b6a7-fbe25b006ad0">
좌: 개발된 상태 / 우: 피그마

2023-08-01 13:52 UTC, prectal123 approved these changes
LGTM 입니다
사소하지만 하이퍼링크 기능도 고려해주세요!

2023-08-01 17:18 UTC, SnowSuno requested changes

2023-08-01 17:18 UTC, SnowSuno commented on client/src/components/atoms/TextArea.tsx
> +};
요런식으로 하면 조금 더 간결할 것 같아요
```suggestion
export const TextArea = styled(Text)`
  width: 100%;
  outline: none;
`;

TextArea.defaultProps = { contentEditable: true };
```

2023-08-01 17:18 UTC, SnowSuno commented on client/src/components/organisms/ChatContainer.tsx
> +import { Message } from "biseo-interface/chat";
type 만을 import 하는 경우 `import type` 문법을 사용하는 것이 좋아요
runtime에서 사용되는 코드가 아니기에 typescript 컴파일 시에 삭제됩니당

또한 비서에서는 `biseo-interface`에 타입만을 의존하고 있기 때문에 `biseo-interface/~~~`에서 import 하는 경우 무조건 `import type`을 사용한다고 생각하면 될 것 같아요
```suggestion
import type { Message } from "biseo-interface/chat";
```

2023-08-01 17:18 UTC, SnowSuno commented on client/src/components/organisms/ChatContainer.tsx
> +            <ChatNotice {...data} />
이런 array를 렌더링하려고 하는 경우에는 `key` prop을 제공해줘야 해요
https://react.dev/learn/rendering-lists

`key`는 unique 해야 하니까 위에 있는 가짜데이터도 수정해줘야겠죠

```suggestion
            <ChatMessage key={data.id} {...(data as Message)} />
          ) : (
            <ChatNotice key={data.id} {...data} />
```

2023-08-01 17:20 UTC, SnowSuno requested changes
읽어보고 코멘트 남겼어용

2023-08-01 17:53 UTC, SnowSuno approved these changes
LGTM 🐶

2023-08-01 17:53 UTC, SnowSuno approved these changes
LGTM 🐶

2023-08-01 17:53 UTC, merged