PR for Terminated Agendas UI
sparcs-kaist/biseo pull request #25
Opened 2023-07-27 06:52 UTC by prectal123

This is the PR for the UI development of Terminated Agendas, the section of the central part of the main page of Biseo v2.0.

ref : https://www.figma.com/file/xecWTLqNnHpxFXpa66YeqI/Biseo2.0?type=design&node-id=0-1&mode=design&t=TWvkeqGBH9PZss2i-0

2023-07-27 13:02 UTC, minjoo0729 commented
<img width="257" alt="biseo" src="https://github.com/sparcs-kaist/biseo/assets/114305937/4fabfbcd-a429-4746-973b-c5103a063814">
[molecules]
- [ ] tag1
- [ ] tag2
- [ ] tag3
[organisms]
- [ ] folded_box

태그 이름들은 정해지면 바꾸겠습니당

2023-07-27 14:57 UTC, prectal123 commented
![Choice](https://github.com/sparcs-kaist/biseo/assets/49473889/8e2c72a9-0abf-40d9-99d6-8fe64e92b294)

2023-07-27 14:57 UTC, Ariaspect commented
<img src="https://github.com/sparcs-kaist/biseo/assets/101387210/ae316b93-b974-4599-8e0c-7997ada8f70f" width=40%>

2023-07-28 17:16 UTC, kjy2844 commented
> <img alt="" width="40%" src="https://user-images.githubusercontent.com/101387210/256577141-ae316b93-b974-4599-8e0c-7997ada8f70f.png">

이미지가 기명투표가 종료되었을 때를 보여주는 것 같습니다.
무기명투표만 구현하기로 했으므로 아래의 이미지를 보고 개발하시면 될 것 같습니다.
<img width="260" alt="스크린샷 2023-07-29 오전 2 12 47" src="https://github.com/sparcs-kaist/biseo/assets/47997136/cf854013-759c-4836-81e4-3926a045d1d2">

2023-07-31 01:22 UTC, minjoo0729 commented
현재까지 구현한 모습
<img width="242" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/114305937/44e3faf2-01a3-49d6-8c2b-4acf9b1a024b">

- atoms/Tag.tsx 파일로 bg 비워둔 Tag component 추가
- molecules 레벨에서는 Tag 3개를 담은 AgendaTag.tsx, 제목 및 내용을 담은 AgendaFoldedText.tsx 추가
- organism 레벨에서는 AgendaTag와 AgendaFoldedText를 담은 AgendaFoldedCard 추가
- theme에 purple200, purple600, gray600 추가(피그마에는 각각 purple-light, purple로 정의되어있음)

- [ ] atoms/molecules/organism 레벨의 기준?
- [ ] Card component의 clickable이 어떤 의미, 구현 의도?
- [ ] AgendaFoldedCard가 clickable인 경우 hover시에 bg 색이 바뀌는 것이 맞나용?

2023-07-31 13:24 UTC, babycroc commented on client/src/components/molecules/AgendaTag.tsx
> +      <Box dir={"row"} gap={8} align={"center"}>
다른 코드랑 consistent하게 dir={"row"} 말고 dir="row" 처럼 바꿔주시면 좋을 것 같아용 align도 마찬가지

2023-07-31 13:26 UTC, babycroc commented on client/src/components/molecules/AgendaTag.tsx
혜원이한테 물어봐야겠지만 제가 봤을 때 디자인이 tag type랑 color랑 일대일 연결??되어있는 것 같아서 태그 색깔도 Tags interface 바탕으로 칠하면 될 것 같아요 (현재 기획에서 예외가 있을지는 모르겠어요)
-> public이 true이면 color를 orange로 하는 식으로!! 근데 이건 다른 분들 의견도 받으면 좋을 것 같아용

2023-07-31 13:34 UTC, babycroc commented on client/src/components/pages/MainPage.tsx
> -    <ChatSection />
ChatSection import했는데 현재 unused라서 (이러면 lint 에러 뜨나..?) 요거 없애지 말고 살려두면 좋을 것 같아요

2023-07-31 15:15 UTC, Ariaspect commented on client/src/components/pages/MainPage.tsx
> +import { AgendaFoldedTest, AgendaSection, ChatSection } from "@/components/organisms";
https://github.com/sparcs-kaist/biseo/blob/f548a78e5f8ce0ab273cbf4fd8803d06cf24247b/client/src/components/organisms/AgendaFoldedCard.tsx#L20C1-L20C50
export 한 함수 이름과 파일 이름이 동일하지 않아서 그런거같네요

2023-08-01 16:32 UTC, Ariaspect commented on client/src/components/atoms/Tag.tsx
> 혜원이한테 물어봐야겠지만 제가 봤을 때 디자인이 tag type랑 color랑 일대일 연결??되어있는 것 같아서 태그 색깔도 Tags interface 바탕으로 칠하면 될 것 같아요 (현재 기획에서 예외가 있을지는 모르겠어요) -> public이 true이면 color를 orange로 하는 식으로!! 근데 이건 다른 분들 의견도 받으면 좋을 것 같아용

`<Tag type=[type] />`
`type: "hidden" | "_hidden" | "anonymous" | "_anonymous" | "votable" | "empty"`
public은 예약어로 에러뜨길래 hidden으로 바꿨습니당. 언더스코어는 not을 의미하는데 만약 다른 이름을 넣어줄 수 있다면 바꿔도 될거같아요.

2023-08-01 16:37 UTC, Ariaspect commented on client/src/components/organisms/AgendaCard.tsx
@minjoo0729 AgendaFoldedCard 의 내용을 AgendaCard 에 합치고 토글 방식으로 전환할 수 있도록 수정했습니다

2023-08-02 11:22 UTC, prectal123 commented on client/src/components/molecules/AgendaFoldedText.tsx
>    return (
순호가 이야기했던 거긴하지만, ({ agenda }) => { return ( ... ) } 은 ({ agenda }) => ( ... ) 이런 식으로 작성하는게 보기 좋다고 해요

2023-08-02 11:37 UTC, prectal123 commented
지금까지의 커밋들은 LGTM입니다. 코드 정리하고 Tag 부분 만드는데 고생하셨네요

2023-08-02 13:06 UTC, minjoo0729 commented
Tag 부분 정리가 너무 깔끔해요!!
수고하셨습니당 :)

2023-08-02 16:14 UTC, prectal123 commented
마지막 커밋을 해준 @Ariaspect 의 이야기가 아직 없었지만, UI가 완성된 것으로 보여지기 때문에 PR Ready를 하겠습니당
![Folded](https://github.com/sparcs-kaist/biseo/assets/49473889/e6b167c5-87e9-40f8-a3bd-83f2df371949)
![Open](https://github.com/sparcs-kaist/biseo/assets/49473889/21b8d312-75e4-41b2-b72c-537f35c02f6d)

2023-08-02 16:18 UTC, prectal123 commented
최다 득표 하이라이트나 본인이 선택한 항목 표시 등에 대한 변경 사항은 디자인이 확정된 후 다른 Branch에서 진행하도록 하겠습니다

2023-08-02 17:31 UTC, babycroc commented on client/src/components/molecules/AgendaFoldedText.tsx
>    return (
https://github.com/sparcs-kaist/biseo/pull/27#discussion_r1281859459 참고!

2023-08-02 17:41 UTC, babycroc requested changes
오왕 고생하셨습니다!! 코멘트 단거랑 순호가 말한 pure component인 거는 바로 return해버리기만 되게끔 수정해주면 좋을 것 같아요 :)

2023-08-02 17:41 UTC, babycroc commented on client/src/components/organisms/AgendaCard.tsx
> +    <Card primary clickable onClick={() => setEnabled(enabled => !enabled)}>
요거 card거 아마 `border-radius`가 10px이었던 것 같은데 혜원이의 대부분의 디자인에는 5px이었어서.. `Card.tsx`에서 바로 5px로 바꾸던지 아니면 `Box`처럼 `round` prop을 만들어서 넘겨주던지 하면 좋을 것 같아요

2023-08-02 17:41 UTC, babycroc commented on server/yarn-error.log
오잉 요건 왜 들어간거지 요 파일이랑 `yarn-error.log` 둘 다 지워주면 좋을 것 같아요!!

2023-08-02 21:28 UTC, SnowSuno requested changes

2023-08-02 21:28 UTC, SnowSuno commented on client/src/components/molecules/AgendaDetail.tsx
> +}
`Agenda`라는 타입은 이미 다른 스키마로 정의되어 있어서 같은 네이밍을 쓰면서 여기에서 이렇게 다른 타입으로 정의하는 것은 혼란스러울 수 있을 것 같아요.

`AgendaFoldedText.tsx` 파일에도 동일한 이름으로 다르게 타입이 정의되어 있어서 더더욱 이런 상황은 피하는게 좋을 것 같아요!

2023-08-02 21:28 UTC, SnowSuno commented on client/src/components/molecules/AgendaDetail.tsx
> +}
이 케이스의 경우에는 agenda의 `title`, `subtitle`, `content` 정보만 필요한 것이라면 새로운 `Agenda` 타입을 정의하는 것보다는 각각의 필드로 나누어서 받는 것이 explicit해서 좋을 것 같아요.

컴포넌트를 사용하는 쪽에서 생각해보면 `agenda={agenda}`와 같이 prop을 넘겨주려 할 때 서로 다른 `Agenda` 타입을 가지고 있도록 정의하면 헷갈릴 것 같네요

```suggestion
interface Props {
  title: string;
  subtitle: string;
  content: string;
}
```

2023-08-02 21:28 UTC, SnowSuno commented on client/src/components/molecules/AgendaFoldedText.tsx
> +}
이 부분도 위 코멘트에서 언급한 대로 고치는게 좋을 것 같아요!

```suggestion
interface Props {
  title: string;
  subtitle: string;
}
```

2023-08-02 21:28 UTC, SnowSuno commented on client/src/components/molecules/AgendaTag.tsx
> +}
이 부분도 동일합니당
```suggestion
interface Props {
  hidden: boolean;
  anonymous: boolean;
  votable: boolean;
}
```

2023-08-02 21:28 UTC, SnowSuno commented on server/yarn-error.log
.gitignore에 `*.log`를 추가해야 할 것 같네요

2023-08-02 21:28 UTC, SnowSuno commented on client/src/components/molecules/AgendaTag.tsx
> +      <Tag type={tags.votable ? "votable" : "empty"} />
태그를 렌더하고 싶지 않은 것이라면 tag에 `empty` type을 만드는 것보다는 아예 렌더하지 않으면 되지 않을까요?
```suggestion
      {tags.votable && <Tag type="votable" />}
```

2023-08-02 21:30 UTC, SnowSuno commented
`TerminatedAgenda` 결과 그래프 부분은 아마 상당수 바뀌는 부분이 있을 것 같아서 따로 리뷰하지 않았습니당

~코드리뷰 너무 힘들어요 오래걸려 힝~

2023-08-04 07:34 UTC, Ariaspect commented on client/src/components/atoms/Tag.tsx
오브젝트에선 문제가 없었는데 styled.div를 만드는 부분에서 타입까진 괜찮은데 초기값 설정해주는 부분에서 그렇더라구요.. 
```js
const TagInner = styled.div<{
  public: boolean;    // ok
  ...
}>(
  ({
    public = true,    // error
    ...
  }) => [
```
근데 구조가 약간 바뀌어서 오브젝트에서만 쓰이기 때문에 public으로 사용해도 괜찮을거 같아요. 이름이 확정된건 아니기때문에 일단 냅둘게요!

public으로 사용해도 문제없다는 부분 확인했습니당.

2023-08-04 07:39 UTC, Ariaspect commented on client/src/components/molecules/AgendaDetail.tsx
> +}
맞아요. 지금 대부분의 컴포넌트에 있는 인터페이스는 테스트용 코드라서 로직 작업할때 프론트에서 가져다쓰기 편한 형태로 함께 고치기로 했습니당.

2023-08-04 07:54 UTC, Ariaspect commented on client/src/components/atoms/Tag.tsx
> +type Types = keyof typeof tagStyles;
```js
type TagTypes = "public" | "private" | "identified" | "anonymous" | "votable";
```
이정도 네이밍으로 가도록 하겠습니당

2023-08-04 12:10 UTC, SnowSuno reviewed
지난 리뷰하게 빠진 부분이 있어서 간단하게 코멘트했습니당

2023-08-04 12:10 UTC, SnowSuno commented on client/src/components/atoms/Tag.tsx
> +} as const;
`as const` 키워드를 사용하는것보단 '`TagTypes`를 키로 가지고 value가 string인 object'를 의미하는 `Record<TagTypes, string>`을 쓰면 좋을 것 같아요!

이렇게 하면 `TagTypes`가 바뀌었을 때 대응하기 용이해집니당
```suggestion
const tagNames: Record<TagTypes, string> = {
  public: "공개",
  private: "비공개",
  identified: "기명",
  anonymous: "무기명",
  votable: "투표 가능",
};
```
전 리뷰에도 슥끼어들어가있긴 했는데 설명이 부족했던 것 같네요ㅠㅠ

2023-08-04 12:18 UTC, babycroc reviewed
나아는 추가할 코멘트는 없구 저번에 코멘트 단거 반영 안된거 하나 잇긴 한데 (VoteDetail에 있는거 그거만 반영해주면 될 것 같아요) 수고했어요!!! 🙃

2023-08-04 12:22 UTC, babycroc commented on client/src/components/organisms/AgendaCard.tsx
> +    <Card primary clickable onClick={() => setEnabled(enabled => !enabled)}>
짱이야

2023-08-04 13:37 UTC, babycroc reviewed
옹 해치웠나 LGTM!

2023-08-04 13:38 UTC, babycroc approved these changes

2023-08-04 13:39 UTC, merged