style login page
sparcs-kaist/biseo pull request #259
Opened 2023-08-26 09:05 UTC by hye1ee

- style basic components

2023-08-26 09:35 UTC, babycroc requested changes

2023-08-26 09:35 UTC, babycroc commented on client/src/components/pages/LoginPage.tsx
> +import { Box, Text } from "../atoms";
Import 형식 통일

2023-08-26 09:37 UTC, babycroc commented
개발 현황 사진 첨부해주세용

2023-08-26 13:51 UTC, babycroc commented on client/src/components/pages/LoginPage.tsx
> +const InputContainer = styled.input`
요거 text styling도 필요하겠다
TextInput atom 만든거 여기도 쓸 수 있으면 그거 사용하는 게 나을지도?

2023-08-27 04:16 UTC, hye1ee commented on client/src/components/pages/LoginPage.tsx
> +const InputContainer = styled.input`
@babycroc text atom확인했는데 로그인 페이지에만 쓰이는 (원래 디자인 시스템에 없던) 사이즈라, 괜히 건드리지 않고 새로 임시로 만들어뒀어

2023-08-27 04:54 UTC, babycroc approved these changes

2023-08-27 15:58 UTC, babycroc approved these changes

2023-08-27 15:58 UTC, babycroc commented
width responsive 관련 이슈 만들어둠

2023-08-27 17:09 UTC, merged