feat: add react-select
sparcs-kaist/biseo pull request #305
Opened 2023-08-28 04:52 UTC by Ariaspect

Resolves #304

2023-09-13 15:19 UTC, Ariaspect commented
태그 x 버튼 hitbox 가 너무 작은거 같기도 하네요.. 거의 정확히 눌러야 되는 수준이에요.
padding을 늘리면 될려나

2023-09-13 15:35 UTC, babycroc requested changes
헿 내가 포기한 ui 구현하느라 수고했엉

2023-09-13 15:35 UTC, babycroc commented on client/src/assets/index.ts
logoLargeIcon이랑 naming consistency를 맞춥시다!
개인적으로 smallClose가 말이 되는 것 같긴 한데 파일 순서 봤을 때 같은놈들이 몰려있으면 좋으니(?) closeSmall로 바꾸는 건 어떨까용
어차피 icon refactor도 하려고 했었어서 당장 크게 상관은 없을 것 같긴 해요

2023-09-13 15:35 UTC, babycroc commented on client/src/assets/smallclose.svg
요거 filename도 camelcase로

2023-09-13 15:35 UTC, babycroc commented on client/src/components/atoms/PresetOption.tsx
> +    bg={selected ? "blue100" : "white"}
오잉 딴 건 다 selected가 gray100인데 얜 왜 블루지 좀 궁금한걸 @hye1ee

2023-09-13 15:35 UTC, babycroc commented on client/src/components/atoms/PresetOption.tsx
> +import { Box } from "./Box";
import 형식 통일! 어차피 바뀔 부분이긴 하지만 그래도 ㅎㅎ

2023-09-13 15:35 UTC, babycroc commented on client/src/components/organisms/CreateAgendaModal.tsx
> +    setSelectedTags(selection);
https://sparcs.slack.com/archives/C01RC6QMSL8/p1694580896447669
요 슬랙 스레드에 관련 논의가 있는 것 같은데 여기도 useCallback을 적용할 수 있지 않을까? (잘 모름, 확신 없음)

2023-09-13 15:36 UTC, babycroc commented
> 태그 x 버튼 hitbox 가 너무 작은거 같기도 하네요.. 거의 정확히 눌러야 되는 수준이에요. padding을 늘리면 될려나

움 그러게 전체적으로 아이콘들이 좀 작아보이긴 하당

2023-09-14 12:35 UTC, Ariaspect commented on client/src/components/atoms/PresetOption.tsx
> +import { Box } from "./Box";
atoms 내부에서 `@/component/atoms` 에서 import 하면 `dependency cycle` 에러 뜨면서 안되길래 일단 이렇게 해놨어요.
금방 없애고 CSS 토큰으로 바꿀게요.

2023-09-14 13:59 UTC, withSang commented on client/src/components/atoms/Label.tsx
> +export const LegacyTagSelect = styled.select`
앞으로 사용할 일 없으니까 지우셔도 좋을 것 같아요!

2023-09-14 14:04 UTC, Ariaspect commented
CSS Token 을 이용해서 그나마 깔끔하게 정리해봤습니다

2023-09-18 17:37 UTC, withSang approved these changes
우와아앙 해결하시느라 정말 고생하셨습니다!

2023-09-19 04:24 UTC, babycroc commented
@SnowSuno 먼가 중요한 건 다 고쳐진 것 같은데 import 형식 통일만 됐으몀 좋겠어요 그럼 일단 머지하고 자잘한 건 이슈로 남기면 될듯

2023-09-19 04:26 UTC, babycroc approved these changes
죠아요
아직 못 건드린 부분이 있다면 이슈로 남겨쥬세용

2023-09-19 04:30 UTC, merged