모달 div로 재구현
sparcs-kaist/biseo pull request #342
Opened 2023-09-11 14:25 UTC by withSang

## Summary
It fixes #58, fixes #64, fixes #261
모달을 dialog로 구현했을 때 발생하는 문제들(이슈 참조)을 해결하기 위해 모달을 div 컴포넌트로 바꾸었습니다.

## Screenshots
- 모달 바깥을 클릭했을 때 잘 닫히는 모습
![화면 기록 2023-09-12 오전 5 23 13](https://github.com/sparcs-kaist/biseo/assets/46402016/de9e49b3-d680-4a4b-bdb8-99d4f8ad98bc)

## Further works
- https://github.com/sparcs-kaist/biseo/issues/304 : 모달 내에서 react-select 드롭다운이 제대로 표시되지 않는 문제가 모달을 div로 다시 구현함으로써 해결될 수 있습니다.

2023-09-11 20:29 UTC, withSang commented on client/src/components/molecules/Modal.tsx
> +/** 모달 내 container에 사용할 스타일을 정의합니다. */
다른 데서 재사용할 일이 없을 것 같아서 기존 styled로 선언된 스타일을 거의 그대로 옮겼어요. 혹시 `styles/`에 선언된 css token들을 더 사용하는 게 좋을까요?

2023-09-11 20:30 UTC, withSang commented on client/src/components/molecules/Modal.tsx
> +      onKeyUp={closeModal}
onClick 리스너를 추가했지만 키보드 이벤트에 대한 리스너를 추가하지 않으면 [jsx-a11y/click-events-have-key-events](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/fffb05b38c8eee926ee758e9ceb9eae4e697fbdd/docs/rules/click-events-have-key-events.md) 규칙에 위배된다고 합니다.

2023-09-11 20:32 UTC, withSang commented on client/src/styles/size.ts
> +    (value: Size) => css`
number, "fill", "hug"에 대해 함수 프로토타입을 통일하면 prop으로 width, height를 넘기기 편해져서 이렇게 바꿔봤습니다.

2023-09-12 05:46 UTC, SnowSuno requested changes
👍

2023-09-12 05:46 UTC, SnowSuno commented on client/src/components/molecules/Modal.tsx
> +export interface Props extends PropsWithChildren {
혹시 `Props`를 export 하는 이유가 있나요?
export해야 하는 이유가 없다면 다른 컴포넌트들과 동일하게 export하지 않거나, export 해야한다면 `ModalProps`와 같은 네이밍을 사용하는게 좋을 것 같기도 합니당

2023-09-12 05:46 UTC, SnowSuno commented on client/src/components/molecules/Modal.tsx
> +  background-color: ${colors.white};
```suggestion
  ${bg.white}
```

2023-09-12 05:46 UTC, SnowSuno commented on client/src/components/molecules/Modal.tsx
> +/** 모달 내 container에 사용할 스타일을 정의합니다. */
사용할 수 있는 부분에는 css 토큰을 합쳐서 사용해도 좋을 것 같아요!

아래에 change request로 예시 하나 달아뒀어용

2023-09-12 05:46 UTC, SnowSuno commented on client/src/components/molecules/Modal.tsx
> +            <button type="button" title="모달 닫기" css={[closeButtonStyle]}>
오 form submit 방지용인가요 👍

2023-09-12 05:46 UTC, SnowSuno commented on client/src/styles/size.ts
> + * h("hug")   // fit-content
혹시 요런 변수 방식으로 바꾼 이유가 있나요? Just curious

2023-09-12 05:49 UTC, withSang commented on client/src/components/molecules/Modal.tsx
> +export interface Props extends PropsWithChildren {
어이쿠 에디터에서 "컴포넌트를 다른 파일로 리팩토링" 버튼을 잘못 눌렀는데 그때 export가 붙어버렸어요 ㅠ 찾아주셔서 감사해요

2023-09-12 05:49 UTC, babycroc commented
퇴근하고 확인해볼게요!

2023-09-12 05:50 UTC, withSang commented on client/src/styles/size.ts
> + * h("hug")   // fit-content
number, "fill", "hug"에 대해 함수 프로토타입을 통일하면 prop으로 width, height를 넘기기 편해져서 이렇게 바꿔봤습니다!

2023-09-12 07:54 UTC, withSang commented on client/src/components/molecules/Modal.tsx
> +            <button type="button" title="모달 닫기" css={[closeButtonStyle]}>
오 네네! 단순한 버튼이라서 type을 "button"으로 설정했습니다.

2023-09-12 07:54 UTC, withSang commented on client/src/components/molecules/Modal.tsx
> +  background-color: ${colors.white};
오 감사합니다! 다 바꿔봤어요 :)

2023-09-12 07:54 UTC, withSang commented on client/src/components/molecules/Modal.tsx
> +export interface Props extends PropsWithChildren {
수정했습니다!

2023-09-12 07:55 UTC, withSang commented on client/src/components/molecules/Modal.tsx
> +      onKeyUp={closeModal}
backDrop에 직접 click 이벤트 리스너를 붙이지 않고, document에 mousedown 이벤트 리스너를 붙이는 방식으로 변경했습니다.

2023-09-12 07:55 UTC, withSang commented on client/src/components/molecules/Modal.tsx
> +/** 모달 내 container에 사용할 스타일을 정의합니다. */
오 감사합니다!

2023-09-12 11:11 UTC, babycroc submitted a review, later dismissed
옹 멋져 주석도 짱 친절해😆

2023-09-12 11:15 UTC, babycroc commented
지금 폰이라서 그런데 fixes #261도 해주세용 내가 쓴 이슌데 고쳐졋어

2023-09-12 11:42 UTC, withSang commented
> 지금 폰이라서 그런데 fixes #261도 해주세용 내가 쓴 이슌데 고쳐졋어

우왕 감사합니다! 오잉 어떻게 고쳐진 거지.... dialog 특인가요

2023-09-12 11:43 UTC, babycroc commented
막 배경스크롤 막아서 그런 것 같기도(?) 아닌가 잘 모르겠지만 해결은 된거같아

2023-09-12 11:48 UTC, withSang commented on client/src/components/molecules/Modal.tsx
> +  ${round.xlg}
지금보니까 xlarge의 접두사는 `round.xl`이 맞겠어요;;
https://getbootstrap.kr/docs/5.0/layout/grid/

2023-09-12 15:21 UTC, Ariaspect commented
- https://github.com/sparcs-kaist/biseo/issues/304 요거 제대로 안보이는 부분 workaround 로 Box 에 zIndex: inherit 달아줘서 해결했었는데 div 적용되면 잘 작동하는지 확인해볼게요!

2023-09-12 16:14 UTC, withSang commented
> * [[투표 생성 모달] `react-select` 이용한 태그 다중선택 드롭다운 구현 #304](https://github.com/sparcs-kaist/biseo/issues/304) 요거 아래 컴포넌트에 가려져서 안보이는 문제 workaround 로 Box 에 zIndex: inherit 달아줘서 해결했었는데 div 적용되면 잘 작동하는지 확인해볼게요!

오 좋아요좋아요!! 아마 이제는 menuPortal로 document.body 걸어주면 가려지는 문제 잘 해결될 거예요

2023-09-12 18:47 UTC, SnowSuno approved these changes
👍 LGTM

2023-09-12 18:47 UTC, merged