feat(ui): agenda section grid fix
sparcs-kaist/biseo pull request #373
Opened 2023-09-13 14:12 UTC by donghyo1234

![image](https://github.com/sparcs-kaist/biseo/assets/37005851/fc0b1783-f5fe-4cea-961c-791181694d76)

2023-09-13 14:50 UTC, babycroc commented
옹 근데 이케 바뀌면 css grid를 쓸 이유가 없어지지 않나??? 애초에 왜 grid를 도입했었던거였죠 @SnowSuno

2023-09-13 15:02 UTC, babycroc requested changes

2023-09-13 15:02 UTC, babycroc commented on client/src/components/organisms/AgendaSection.tsx
사실 ongoing이랑 preparing을 div로 감쌀거면 css grid를 쓰는 이유가 없는 것 같아서 좀 찾아봤는데, 
원래대로 child 123로 하는 대신 이 줄을 넣어주면 작동하는 것 같아요!!
`grid-template-rows: auto 1fr;`
두 행이 있을 때 위의 행은 그냥 content height로 잡고, 아래꺼를 필요한 만큼 늘린다는 것 같아요 (`flex-grow: 1` 하듯이)
참고: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows
요 방법도 되는지 한 번 해봐주실 수 있나용

2023-09-13 15:03 UTC, babycroc commented on .husky/pre-commit
오 그리고 이 파일은 왜 생긴거지 (몰라서 궁금해서 묻는거에요!)

2023-09-13 15:55 UTC, donghyo1234 commented on .husky/pre-commit
이걸 안 넣으면 에러가 자꾸 나더라구요ㅠ

2023-09-13 15:56 UTC, donghyo1234 commented on .husky/pre-commit
왜인지는 모르겠습니다

2023-09-13 16:50 UTC, donghyo1234 commented on client/src/components/organisms/AgendaSection.tsx
그리드를 써서 한칸씩 아젠다를 넣으면 종료된 아젠다가 길어졌을 때 진행중인 아젠다랑 예정된 아젠다 사이에 무조건 공백이 생기는 것 같아용
grid-template-rows: auto 1fr; 요것도 첫째 행을 auto로 맞추면 종료된 아젠다도 첫쨰 행이라서 결국 종료된 아젠다보다 아래에 생깁니다

2023-09-13 23:13 UTC, babycroc commented on client/src/components/organisms/AgendaSection.tsx
오잉 상식적으로 생각해보면 그렇네 뭐지 어제 해봤을 땐 되는 것 같은 느낌이었는데.. 그럼 사실 그리드 쓰는 의미가 없는 것 같은데 머 괜찮겠지

2023-09-13 23:14 UTC, babycroc approved these changes

2023-09-13 23:15 UTC, babycroc commented
난 더 해결책이 생각 안 나서 그런데 다른 사람 리뷰도 함 받아보면 좋을 것 같앙

2023-09-13 23:16 UTC, babycroc commented on client/src/components/organisms/AgendaSection.tsx
2열의 1,2행 셀을 머지하는 옵션은 없으려나

2023-09-14 01:00 UTC, babycroc commented on client/src/components/organisms/AgendaSection.tsx
오잉 근데 원래 수정 전 코드에 있던 1/3 이 문법이 그 merging을 해주는거라 생각했는데 내컴에서 해봤을 땐 잘 됐었거덩 다시 함 해봐줄 수 있나 아님 막 span 이런걸로 머지 델거같은데

2023-09-14 09:50 UTC, minjoo0729 requested changes
어제 동방에서 완전 열심히 하던데 고생 많았어요 :)

2023-09-14 09:50 UTC, minjoo0729 commented on client/src/components/organisms/AgendaSection.tsx
> +        </div>
진행중인 투표 섹션이랑 예정된 투표 섹션 사이에 간격만 추가해줄 수 있을까요? 

[현재 상황]
![image](https://github.com/sparcs-kaist/biseo/assets/114305937/5b4c553b-f835-487c-b068-815324889618)
[피그마]
<img width="654" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/114305937/510eadb5-d418-4f8f-b22c-48edb269d3ee">

2023-09-19 04:28 UTC, SnowSuno commented on client/src/components/organisms/AgendaSection.tsx
@babycroc 이 언급한 `grid-template-rows: auto 1fr;`으로 해결되어서 해당 내용으로 올렸습니당

#378

2023-09-19 04:29 UTC, closed without merging