fix: remove emoji
sparcs-kaist/biseo pull request #393
Opened 2023-09-21 21:35 UTC by oganessone718

fixes #232 
일단 이모티콘 버튼 없애봤습니다...! 문제 있다면 알려주세요.

2023-09-24 13:34 UTC, SnowSuno requested changes

2023-09-24 13:34 UTC, SnowSuno commented on package-lock.json
엇 혹시 `npm install` 로 패키지 설치하셨나요? 비서에서는 `pnpm` 쓰고있어서 `npm` 대신 `pnpm` 사용해야 해요!
이 파일은 지워주시면 될 것 같습니당

2023-09-24 13:34 UTC, SnowSuno commented on client/src/components/molecules/ChatInput.tsx
> +// import { EmoticonIcon, SendIcon } from "@/assets";
코드 삭제는 어차피 기록에 남기 때문에 굳이 주석 처리하고 남겨두는 것보다는 아예 지워 주시면 될 것 같아요!

```suggestion
```

2023-09-24 13:34 UTC, SnowSuno commented on client/src/components/molecules/ChatInput.tsx
> +import { SendIcon } from "@/assets"; // remove emoji
코드에 대해서 설명을 남기고 싶을 때는 코드 내에 주석으로 남기는 것보다 깃헙 PR 내에서 자신의 작업사항에 대해서도 댓글을 남길 수 있으니 그렇게 남겨주시면 될 것 같아요!

```suggestion
import { SendIcon } from "@/assets";
```

2023-09-24 13:34 UTC, SnowSuno commented on client/src/components/molecules/ChatInput.tsx
> +        {/* <EmoticonIcon /> */}
```suggestion
```

2023-09-24 13:40 UTC, withSang submitted a review, later dismissed
좋은 것 같습니다! 감사합니다.

2023-09-24 13:40 UTC, withSang commented on client/src/components/molecules/ChatInput.tsx
> +        {/* <EmoticonIcon /> */}
아래처럼 `{/* TODO: Add EmoticonIcon */}` 을 추가해주셔도 좋습니다!

2023-09-24 13:41 UTC, babycroc reviewed
순호랑 상이 코멘트만 반영해주면 좋을 것 같아용! 고생했습니다아

2023-09-25 17:21 UTC, SnowSuno commented on package-lock.json
요거 여전히 안 지워지고 남아있는것 같아용

2023-09-25 17:22 UTC, SnowSuno commented on client/src/components/molecules/ChatInput.tsx
> +        {/* TODO: Add EmoticonIcon */}
👍

2023-09-26 20:52 UTC, Ariaspect commented on package-lock.json
이거 없애려면 `git rm` 커맨드 이용해야해요 그래야 깃허브에서도 지워질거같습니다.

2023-09-27 10:12 UTC, SnowSuno approved these changes
LGTM 👍

2023-09-27 10:14 UTC, withSang approved these changes
LGTV! 🖥

2023-09-29 08:49 UTC, merged