fix: adjust '+' line height to one
sparcs-kaist/biseo pull request #477
Opened 2024-03-20 11:02 UTC by Sanghou

# 요약 \*

It closes [#374](https://github.com/sparcs-kaist/biseo/issues/374)

# 스크린샷

수정 전
<img width="776" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/19489734/1def7761-4e66-4b54-8643-181a93f93e23">

수정 후

<img width="754" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/19489734/d3d3f635-c1e6-4747-a4b5-46a58ca00694">

# 이후 Task \*

- 없음

2024-03-20 11:32 UTC, yumincho requested changes

2024-03-20 11:32 UTC, yumincho commented on packages/web/src/components/molecules/ModalInnerTextBox.tsx
> +      <Text color="blue600" variant="boldtitle2" style={{ lineHeight: 1 }}>
token 사용하지 않고 특정 컴포넌트에만 적용되는 스타일을 작성할 경우 emotion의 `css` 말고 `style`을 사용하는 게 나을까요? 제가 다른 작업할 때 아래와 같은 방식으로 작성해둬서 여쭤봅니다.

```typescript
<Text ... css={[`lineHeight: 1`]} >
```

2024-03-27 10:40 UTC, Sanghou commented on packages/web/src/components/molecules/ModalInnerTextBox.tsx
> +      <Text color="blue600" variant="boldtitle2" style={{ lineHeight: 1 }}>
스타일 하나로 통일할 수 있으면 좋을 것 같습니다.
제가 레퍼런스 했던 코드에서는 style이라서 거기에 맞췄는데 
다른 코드들 보니 css={[]}로 쓰는게 많아서 css로 하는게 통일성 있을 것 같네요!

2024-03-27 11:08 UTC, yumincho approved these changes
토큰으로 바뀐 거 확인했습니다! 수고하셨습니당 👍

2024-03-27 11:21 UTC, merged