Admin Terminated Agenda UI
sparcs-kaist/biseo pull request #57
Opened 2023-08-10 15:34 UTC by prectal123

resolves #56

2023-08-13 15:53 UTC, prectal123 commented
![image](https://github.com/sparcs-kaist/biseo/assets/49473889/5ada4e0e-0b12-4839-8cec-c6c275dcfd94)

2023-08-14 08:00 UTC, minjoo0729 requested changes
우왕 완전 수고하셨습니다

2023-08-14 15:47 UTC, prectal123 commented on client/src/components/organisms/TerminatedAgendaModal.tsx
> +              <OptionVoteResult name="반대" count={2} totalCount={7} w={280} />
피그마와 일일이 대조하기 쉽지 않았을텐데 감사합니다

2023-08-20 14:23 UTC, babycroc requested changes
몇 개 파일은 표시 안했는데 import 형식 통일 안된 부분이 많아서 모든 파일 다 확인해주세요!! 고생햇습니다앙ㅇ

2023-08-20 14:23 UTC, babycroc commented on client/src/components/molecules/AdminOngoingAgendaCard.tsx
> +import { AdminAgenda } from "biseo-interface/admin/agenda";
```suggestion
import type { AdminAgenda } from "biseo-interface/admin/agenda";
```

2023-08-20 14:23 UTC, babycroc commented on client/src/components/molecules/AdminOngoingAgendaCard.tsx
>  import type { OngoingAgenda } from "biseo-interface/agenda";
요건 안쓰이는건강 그럼 빼주세요

2023-08-20 14:23 UTC, babycroc commented on client/src/components/molecules/AdminTerminatedAgnedaCard.tsx
파일명에 오타 고쳐주세요오 힝

2023-08-20 14:23 UTC, babycroc commented on client/src/components/molecules/AdminTerminatedAgnedaCard.tsx
> +import { AdminAgenda } from "biseo-interface/admin/agenda";
`biseo-interface`에서 import한 건 `type` 붙이구 나머지는 다른 파일처럼 `@/components/~~`로 형식 맞춰주세요!!

2023-08-20 14:23 UTC, babycroc commented on client/src/components/molecules/ModalInnerTextBox.tsx
> +import { BorderedBox, Box, Text, TextArea } from "../atoms";
요기둥

2023-08-20 14:23 UTC, babycroc commented on client/src/components/molecules/ParticipantBar.tsx
> +import { BorderedBox, Box, Text, TextArea } from "../atoms";
얍

2023-08-20 14:23 UTC, babycroc commented on client/src/components/organisms/AdminAgendaSection.tsx
요기도 import~

2023-08-20 14:23 UTC, babycroc commented on client/src/services/admin-agenda.ts
먼가 민준이 피알 순호 코멘트에서 봤던 것 같은데 `export { useAdminAgenda }` 보다는 `export const useAdminAgenda = ...` 요렇게 바꾸라고 햇던 것 같기도..

2023-08-20 14:24 UTC, babycroc commented on client/src/components/organisms/TerminatedAgendaModal.tsx
> +              <OptionVoteResult name="반대" count={2} totalCount={7} w={280} />
민주 진짜 짱이야 꼼꼼해 멋져

2023-08-21 12:41 UTC, merged