Feat/admin preparing agenda UI
sparcs-kaist/biseo pull request #69
Opened 2023-08-13 14:32 UTC by donghyo1234

Feat/admin preparing agenda UI 개발

2023-08-14 16:04 UTC, donghyo1234 commented
![image](https://github.com/sparcs-kaist/biseo/assets/37005851/79cc3f85-9135-4efa-b359-aa1f7b50785c)

2023-08-14 16:05 UTC, donghyo1234 commented
![image](https://github.com/sparcs-kaist/biseo/assets/37005851/e71d5c03-45d1-411e-a852-8fb97551ca60)

2023-08-17 05:22 UTC, babycroc requested changes
조아용! 코멘트를 남기긴 했는데 일단 한번 머지 후에 리팩토링에서 해도 되는 작업들이기는 해서 해당 피알에서 당장 처리할 게 아니라면 잊지 않게 이슈에 등록해주세용 고생하셨습니당

2023-08-17 05:22 UTC, babycroc commented on client/src/assets/plusIcon.svg
다른 svg file들이랑 naming 형식 통일하자!

2023-08-17 05:22 UTC, babycroc commented on client/src/components/atoms/NewAgendaButton.tsx
뭔가 순호한테 주워듣기로 버튼 같은 거 만들 때 div 말고 button tag 써서 styling하면 button이 가지고 있는 고유 기능(?)들을 그대로 쓸 수 있어서 좋다고 들었어요!! 예를 들면 hover 했을 때 cursor 바뀌어서 clickable하게 느껴지는 뭐 그런 사소한 디테일들에 차이가 있을 것 같기도 하구.. 생각나서 말씀드려봤습니당

2023-08-17 05:22 UTC, babycroc commented on client/src/components/atoms/NewAgendaButton.tsx
그리구 요 버튼 모양이 new agenda 뿐만 아니라 new 머시기머시기 (템플릿, 프리셋 등등) 공통으로 쓰일 수 있을 것 같아서 파일명에서 agenda라는 단어를 빼도 좋을 것 같고, 요 버튼의 prop으로 "button text" 같은 거만 받아오고 plusIcon도 이 파일에서 import해서 display하면 어떨까요?

2023-08-17 05:22 UTC, babycroc commented on client/src/components/atoms/NewAgendaButton.tsx
미래의 얘기긴 하지만 나중에는 button.tsx에 요런 스타일링을 프롭으로 전달하게 하고 요 파일은 button을 확장해서 만들게끔 리팩토링을 해도 좋을 것 같군요

2023-08-17 05:22 UTC, babycroc commented on client/src/components/molecules/AdminPreparingAgendaCard.tsx
요 파일에 adminongoindagendacard랑 같은 부분이 많은 것 같은데 일단 머지한 다음에 중간에 agendacard 컴포넌트를 만들던지 해서 리팩토링을 하면 좋을 것 같아요

2023-08-17 05:22 UTC, babycroc commented on client/src/components/organisms/AdminAgendaSection.tsx
> +import { PlusIcon } from "@/assets";
아까도 언급했지만 요거는 NewAgendaButton 파일로 넣어주자!

2023-08-17 05:22 UTC, babycroc commented on client/src/components/organisms/AdminAgendaSection.tsx
> +  ));
preparingAgendas가 없을 때의 UI도 만들어야하는군
당장 할 작업이 아니라면 까먹지 않게 이슈에 등록해주세요!

2023-08-20 12:09 UTC, donghyo1234 commented
![image](https://github.com/sparcs-kaist/biseo/assets/37005851/b905dc7d-6c78-4757-88f2-f10e9099c8b9)
![image](https://github.com/sparcs-kaist/biseo/assets/37005851/da96c28c-ee6d-4ea5-9da0-0de572ad3532)

2023-08-21 13:14 UTC, merged